const brandMap: Record<string, string> = {
    PYTHON: 'python',
    TYPESCRIPT: 'typescript',
    JAVASCRIPT: 'javascript',
    SQL: 'postgresql',
    MONGODB: 'mongodb',
    'REACT.JS': 'react',
    REACT: 'react',
    'REDUX TOOLKIT': 'redux',
    'NEXT.JS': 'nextdotjs',
    'TAILWIND CSS': 'tailwindcss',
    'NODE.JS': 'nodedotjs',
    'EXPRESS.JS': 'express',
    AWS: 'amazonaws',
    'PRISMA ORM': 'prisma',
    TENSORFLOW: 'tensorflow',
    PYTORCH: 'pytorch',
    'HUGGINGFACE TRANSFORMERS': 'huggingface',
    'SCIKIT-LEARN': 'scikitlearn',
    XGBOOST: 'xgboost',
    OLLAMA: 'ollama',
    LANGCHAIN: 'langchain',
    PANDAS: 'pandas',
    NUMPY: 'numpy',
    MLFLOW: 'mlflow',
    PANDAPOWER: 'pandas',
    DOCKER: 'docker',
    LINUX: 'linux',
    K6: 'k6',
    GITHUB: 'git',
    'GITHUB ACTIONS (CI/CD)': 'githubactions',
    JEST: 'jest',
    PYTEST: 'pytest',
    SELENIUM: 'selenium',
    GIT: 'git',
    SQLITE: 'sqlite',
    GRAFANA: 'grafana'
};

export const getBrandSlug = (name: string): string => brandMap[name] || '';