# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js + Vite static deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # minimal permission
      id-token: write # required for OIDC
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i 
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test jest not configured yet
    #pulled the github pages site action from actions...
    - name: Upload GitHub Pages artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./dist
        overwrite: true
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
      #   #GitHub token with permissions to deploy to GitHub Pages (default: GITHUB_TOKEN)
      #   token: GITHUB_TOKEN
      #   #Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
      #   timeout: 600000
      #   #Maximum number of status report errors before cancelling a deployment (default: 10)
      #   error_count: 10
      #   #Time in milliseconds between two deployment status report (default: 5 seconds)
      #   reporting_interval: 5000
      #   #Name of the artifact to deploy
        artifact_name: github-pages
      #   #Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
      #   preview: false
          
